# Generated by Django 5.2.1 on 2025-05-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prenom')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Coureur',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.membre')),
                ('dossard', models.IntegerField(verbose_name='dossard')),
            ],
            bases=('courses.membre',),
        ),
        migrations.CreateModel(
            name='EntraineurMembre',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.membre')),
            ],
            bases=('courses.membre',),
        ),
        migrations.AddField(
            model_name='membre',
            name='appartient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.equipe'),
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_arrivee', to='courses.ville')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_depart', to='courses.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortie', models.CharField(choices=[('Abandon', 'Ab'), ('Accident', 'Ac'), ('Disqualification', 'Di')], max_length=100)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.etape')),
                ('coureur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coureur')),
            ],
        ),
        migrations.AddField(
            model_name='coureur',
            name='entraineur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.entraineurmembre'),
        ),
    ]
